language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: BoCvQuu5Y6FuYaeyiJRII+WjTMa1ZU6IDNyj/D1v4EGYVlE/KJX9neWplmd5vlwNlKPGadqs1KcKpK9drpImnWZ8TLMKbsHADei6p+DDHkflbAa+o/MhXv+dDgFel0yUDY9tEx3R6aWlMxW/0GEq+SHmcmlho4RPB+ELad98VHod+wV563Mplri+8V+w/UnxggX+SJWBPg2ZGo3ng9VkCJQTeLRoVpaDW967WNO35ArfeP2AMyV2+L7GQkZS2rLQx7dOiPGlSaa7AQDwqMLs0zR0VJBh3ybDFlWWo2aTK9RBFvCcWc3X+VBxkcEV4o8nq33iZZF9/Fe4rQ9RgK1W3UD4ohGIU230T6e0w0hBwNVEGaFmQVpSUNg7ccp/cuVNrQK/+X2zJkDbBkiWh4OWtet+ZKdzsXghuZ0+HG7gVs+FlFz2eY2OJ90bJKLgGtieeNHIHE+He4Uo5Zw2E+vAxIksZTb8BE3quY3es8wv7+K+5OhwEgJ2RrP6Hj3yfxeGTUM6znc0QYrF6CLg8gaHHlOghnz7W47RL5Kf8/DAFjswpfdLgB9Q0XAfsF8EILhQWJxK99cXhIJ4QV7wjGpcjOgei3Q5hIwUtgu3cCI0Ug7Cw+yrQXU7IBTmwv6eZ5f1N78Qx4hrS8ReEGKz3T0xyZllfGo4yvfSPa56mE9u0as=
  app: evening-dawn-40045
